# Generated by Django 3.1.7 on 2021-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], db_index=True, default='seller', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
