# Generated by Django 3.1.7 on 2021-03-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210302_1315'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
